---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sonarr
namePrefix: sonarr-

resources:
  - ./sonarr.yml

components:
  - ../../components/nas-media

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - sonarr.yml=gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: sonarr
