---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: valkey-

resources:
  - ./valkey.yml

components:
  - ../../components/pod-hardening

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/component: valkey
