---
- op: add
  path: /spec/template/spec/volumes/0
  value:
    name: nas
    persistentVolumeClaim:
      claimName: nas
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/0
  value:
    name: nas
    mountPath: /media
    # subPath: media
