---
TV Show:
  '3Blue1Brown': 'https://www.youtube.com/@3blue1brown'
  'Action Retro': 'https://www.youtube.com/@ActionRetro'
  'Aging Wheels': 'https://www.youtube.com/@agingwheels'
  'Ambition Strikes': 'https://www.youtube.com/@AmbitionStrikes'
  'Berm Peak': 'https://www.youtube.com/@SethsBikeHacks'
  'BibleProject': 'https://www.youtube.com/@bibleproject'
  'Brick Experiment Channel': 'https://www.youtube.com/@BrickExperimentChannel'
  'Bringus Studios': 'https://www.youtube.com/@BringusStudios'
  'Cameron Grey': 'https://www.youtube.com/@camerongray1515'
  'CGP Grey': 'https://www.youtube.com/@CGPGrey'
  'Cleo Abram': 'https://www.youtube.com/@CleoAbram'
  'Craft Computing': 'https://www.youtube.com/@CraftComputing'
  'Dan Becker': 'https://www.youtube.com/@DanBecker'
  'Garage Grown Gear': 'https://www.youtube.com/@garagegrowngear'
  'Geerling Engineering': 'https://www.youtube.com/@GeerlingEngineering'
  'Hardware Haven': 'https://www.youtube.com/@HardwareHaven'
  'Hike, Camp, Cook': 'https://www.youtube.com/@HikeCampCook'
  'I Like To Make Stuff': 'https://www.youtube.com/@Iliketomakestuff'
  'James Hoffmann': 'https://www.youtube.com/@jameshoffmann'
  'Jeff Geerling': 'https://www.youtube.com/@JeffGeerling'
  'JerryRigEverything': 'https://www.youtube.com/@JerryRigEverything'
  'Jon Bringus': 'https://www.youtube.com/@JonBringus'
  'Justin Outdoors': 'https://www.youtube.com/@JustinOutdoors'
  'Justinthetrees': 'https://www.youtube.com/@Justinthetrees'
  'Level 2 Jeff': 'https://www.youtube.com/@Level2Jeff'
  'Made With Layers': 'https://www.youtube.com/@MadeWithLayers'
  'Marius Hornberger': 'https://www.youtube.com/@MariusHornberger'
  'Mark Rober': 'https://www.youtube.com/@MarkRober'
  'Matt Whitman and The Ten Minute Bible Hour': 'https://www.youtube.com/@MattWhitmanTMBH'
  'Matthias Random Stuff': 'https://www.youtube.com/@matthiasrandomstuff2221'
  'Matthias Wandel': 'https://www.youtube.com/@matthiaswandel'
  'MH Anything': 'https://www.youtube.com/@MHAnything'
  'Michael MJD': 'https://www.youtube.com/@MichaelMJD'
  'Minute Earth': 'https://www.youtube.com/@MinuteEarth'
  'Minute Food': 'https://www.youtube.com/@MinuteFood'
  'Minute Physics': 'https://www.youtube.com/@MinutePhysics'
  'Miranda Goes Outside': 'https://www.youtube.com/@MirandaGoesOutside'
  'My Life Outdoors': 'https://www.youtube.com/@MyLifeOutdoors'
  'My Mechanics Insights': 'https://www.youtube.com/c/mymechanicsinsights'
  'My Mechanics': 'https://www.youtube.com/@mymechanics'
  'NetworkChuck': 'https://www.youtube.com/@NetworkChuck'
  'No Boilerplate': 'https://www.youtube.com/@NoBoilerplate'
  'Outdoor Boys': 'https://www.youtube.com/@OutdoorBoys'
  'Playing with Sticks': 'https://www.youtube.com/@PlayingwithSticks'
  'Raid Owl': 'https://www.youtube.com/@RaidOwl'
  'rctestflight': 'https://www.youtube.com/@rctestflight'
  'Sauce+': 'https://www.youtube.com/@sauceplusofficial'
  'SmarterEveryDay': 'https://www.youtube.com/@smartereveryday'
  'SmarterEveryDay2': 'https://www.youtube.com/@smartereveryday2'
  'Snazzy Labs': 'https://www.youtube.com/@snazzy'
  'Speeed': 'https://www.youtube.com/@SpeeedCo'
  'Stand-up Maths': 'https://www.youtube.com/@standupmaths'
  'Steve Mould': 'https://www.youtube.com/@SteveMould'
  'Stuff Made Here 2': 'https://www.youtube.com/@StuffMadeHere2'
  'Stuff Made Here': 'https://www.youtube.com/@StuffMadeHere'
  'Technology Connections': 'https://www.youtube.com/@TechnologyConnections'
  'Technology Connextras': 'https://www.youtube.com/@TechnologyConnextras'
  'The Rest Is Science': 'https://www.youtube.com/@TheRestIsScience'
  'The Stock Pot': 'https://www.youtube.com/@TheStockPot-AU'
  'This Does Not Compute': 'https://www.youtube.com/@ThisDoesNotCompute'
  'thruhikers': 'https://www.youtube.com/@reneeandtim'
  'Veritasium': 'https://www.youtube.com/@veritasium'
  'Woodbrew': 'https://www.youtube.com/@Woodbrew'
  'Zip Tie Tuning': 'https://www.youtube.com/@ZipTieTuning'
  "xkcd's What If?": 'https://www.youtube.com/@xkcd_whatif'

TV Show Collection:
  = Tutorials:
    '~Event Lightning':
      s01_name: 'GrandMA 3 Tutorials'
      s01_url: 'https://www.youtube.com/playlist?list=PLhh6ZoFPnUu1hMCDT2YhuYJxLgW_G0rTn'
    '~Aria Hailey':
      s01_name: 'Phaser Friday'
      s01_url: 'https://www.youtube.com/playlist?list=PLcl55cI1T_GxbwcgzPTvrOZ0-3Gp6_ApB'
      s02_name: 'Timing Tuesday'
      s02_url: 'https://www.youtube.com/playlist?list=PLcl55cI1T_GxPad4tGmZG2lGhtArrI2WX'
  = Christian:
    '~The Promised Land':
      s01_name: 'Season 1'
      s01_url: 'https://www.youtube.com/playlist?list=PLaKYsaAeVpIaO4QGF41-ZvvuG6rPqYPI3'

Music:
  = Christian:
    'Josiah Queen': 'https://www.youtube.com/@josiahqueenmusic/releases'
