apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole
namePrefix: pihole-

resources:
  - ./resources/pihole.yml

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - pihole.yml=gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: pihole
