apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: jellyfin-
namespace: jellyfin
resources:
  - ./resources/config-pvc.yml
  - ./resources/deployment.yml
  - ./resources/service.yml
  - ./resources/ingress.yml

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - jellyfin.yml=gatus.yml
