apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring
namePrefix: grafana-

resources:
  - ./resources/grafana.yml

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - grafana.yml=gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: n8n
