apiVersion: kustomize.config.k8s.io/v1beta1
kind:
  Kustomization

  # - ./cloudflared/app.yml
resources:
  - common.yml
  - ./pihole/app.yml
  - ./external-dns/app.yml
  - ./omada/app.yml
  - ./wg-easy/app.yml
