apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps
namePrefix: karakeep-

resources:
- ./resources/karakeep.yml

configMapGenerator:
- files:
  - karakeep.yml=gatus.yml
  name: gatus
  options:
    labels:
      gatus.io/enabled: "true"

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: karakeep
