---
jobs:
  - name: pvc-drone-01
    type: pull
    root_fs: rust/backup/drone-01
    interval: 10m
    recv: &recv
      placeholder:
        encryption: false
    pruning: &pruning
      keep_sender:
        - type: not_replicated
        - type: regex
          regex: ^manual_.*
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 14x1d
          regex: ^zrepl_.*
      keep_receiver: &keep_receiver
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 35x1d | 6x30d
          regex: ^zrepl_.*
        - type: regex
          regex: ^manual_.*
    connect:
      type: tcp
      address: 192.168.42.21:8889
  - name: pvc-drone-02
    type: pull
    root_fs: rust/backup/drone-02
    interval: 10m
    recv: *recv
    pruning: *pruning
    connect:
      type: tcp
      address: 192.168.42.22:8889
  - name: pvc-drone-03
    type: pull
    root_fs: rust/backup/drone-03
    interval: 10m
    recv: *recv
    pruning: *pruning
    connect:
      type: tcp
      address: 192.168.42.23:8889
  - name: pvc-drone-04
    type: sink
    root_fs: rust/backup/drone-04
    recv: *recv
    serve:
      type: local
      listener_name: localsink
  - name: pvc-source
    type: push
    filesystems: { tank/storage<: true }
    pruning: *pruning
    snapshotting:
      type: periodic
      prefix: zrepl_
      interval: 10m
    connect:
      type: local
      listener_name: localsink
      client_identity: drone-04
  - name: media-snapshots
    type: snap
    pruning:
      keep: *keep_receiver
    snapshotting:
      type: periodic
      prefix: zrepl_
      interval: 1h
    filesystems: { rust/media: true }
