apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storage
namePrefix: wasabi-backup-

resources:
  - ./resources/wasabi-backup.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: wasabi-backup
