---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps
namePrefix: radarr-

resources:
  - ./resources/radarr.yml

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - radarr.yml=gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: radarr
