apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - common.yml
  - ./miniflux/app.yml
  - ./filebrowser/app.yml
  - ./home-assistant/app.yml
  - ./rsshub/app.yml
  - ./frigate/app.yml
  - ./immich/app.yml
  - ./linkding/app.yml
  - ./nextcloud/app.yml
