---
metrics: true

storage:
  type: sqlite
  path: /data/data.db

endpoints:
  - name: gatus
    url: http://gatus-service
    conditions: ['[STATUS] == 200']
    alerts: [{ type: ntfy }]

  - name: google
    url: https://google.com
    conditions: ['[STATUS] == 200']
    alerts: [{ type: ntfy }]

  - name: router
    url: https://192.168.1.1
    group: networking
    client: { insecure: true }
    conditions: ['[STATUS] == 200']
    alerts: [{ type: ntfy }]

alerting:
  ntfy:
    topic: gatus
    url: https://ntfy.beaver-cloud.xyz
    default-alert:
      failure-threshold: 3
      success-threshold: 3
      send-on-resolved: true
