apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: makemkv
namePrefix: makemkv-

resources:
  - ./resources/makemkv.yml

configMapGenerator:
  - name: hooks
    files:
      - ./config/disk_rip_started.sh
      - ./config/disk_rip_terminated.sh
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - makemkv.yml=gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: makemkv
