apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: healthchecks
namePrefix: healthchecks-

resources:
  - ./resources/secret.yml
  - ./resources/drone-01.yml
  - ./resources/drone-02.yml
  - ./resources/drone-03.yml
  - ./resources/drone-04.yml
  - ./resources/unimatrix-01.yml
  - ./resources/unimatrix-02.yml
  - ./resources/unimatrix-03.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: healthchecks
