---
mqtt:
  enabled: false

detect:
  enabled: true

auth:
  enabled: false

ffmpeg:
  hwaccel_args: preset-nvidia-h264

detectors:
  tensorrt:
    type: tensorrt
    device: 0
    model:
      path: /config/model_cache/tensorrt/yolov7-320.trt
      input_tensor: nchw
      input_pixel_format: rgb
      width: 320
      height: 320

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.1/Preview_01_main
          roles: [record]
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.1/Preview_01_sub
          roles: [detect]
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.2/Preview_01_main
          roles: [record]
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.2/Preview_01_sub
          roles: [detect]
