---
mqtt:
  enabled: false

detect:
  enabled: true

auth:
  enabled: false

ffmpeg:
  hwaccel_args: preset-nvidia-h264

detectors:
  onnx:
    type: onnx

record:
  enabled: true
  retain:
    days: 1
    mode: all
  alerts:
    retain:
      days: 2
      mode: motion
  detections:
    retain:
      days: 2
      mode: motion

model:
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt
  width: 320
  height: 320
  input_tensor: nchw
  input_pixel_format: bgr
  model_type: yolonas

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.1/Preview_01_main
          roles: [record]
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.1/Preview_01_sub
          roles: [detect]
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.2/Preview_01_main
          roles: [record]
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.2/Preview_01_sub
          roles: [detect]
  wyze-01:
    ffmpeg:
      inputs:
        - path: rtsp://thingino:thingino@192.168.50.11/ch0
          roles: [record]
  wyze-02:
    ffmpeg:
      inputs:
        - path: rtsp://thingino:thingino@192.168.50.12/ch0
          roles: [record]
