---
mqtt:
  enabled: false

detect:
  enabled: false

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: http://192.168.50.1/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_REOLINK_PASSWORD}
          roles:
            - record
  garage:
    ffmpeg:
      inputs:
        - path: http://192.168.50.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_REOLINK_PASSWORD}
          roles:
            - record
