---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared
namePrefix: cloudflared-

resources:
  - ./cloudflared.yml

components:
  - ../../components/pod-hardening

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: cloudflared
