apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: networking
namePrefix: wg-

resources:
  - ./resources/wg.yml

configMapGenerator:
  - files:
      - wg.yml=gatus.yml
    name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: wg
