---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: networking
namePrefix: wg-

resources:
  - ./resources/wg.yml

configMapGenerator:
  - name: config
    files:
      - ./config/wg0.conf

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: wg
