---
config:
  version: 2
paths:
  media-path: /media
  input-path: /media
  output-path: /media/transcoded
presets:
  show-default-presets: false
  allow-preset-creator: false
application:
  update-check-interval: 0
  queue-startup-behavior: Previous
