---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: node-exporter-
namespace: node-exporter

resources:
  - ./resources/daemon-set.yml

commonLabels:
  app.kubernetes.io/name: node-exporter
