apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns
namePrefix: external-dns-

resources:
  - ./resources/cloudflare-secret.yml
  - ./resources/pihole-secret.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: external-dns
