---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: filebrowser
namePrefix: filebrowser-

resources:
  - ./filebrowser.yml

components:
  - ../../components/nas-media
  - ../../components/pod-hardening

configMapGenerator:
  - name: config
    files:
      - ./config/config.yaml
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - filebrowser.yml=gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: filebrowser
