---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: handbrake-web
namePrefix: handbrake-web-

resources:
  - ./resources/handbrake-web.yml

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - handbrake-web.yml=gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: handbrake-web
