---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: handbrake-web
namePrefix: handbrake-web-

resources:
  - ./handbrake-web.yml

components:
  - ../../components/nas-media
  - ../../components/pod-hardening
  - ../../components/tmpdirs

configMapGenerator:
  - name: config
    files:
      - ./config/config.yaml
      - ./config/presets/super_hq_h265_mkv.json
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - handbrake-web.yml=gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: handbrake-web
