---
global:
  smtp_smarthost: smtp-relay-service.smtp-relay:25
  smtp_from: beavercloud@fastmail.com
  smtp_require_tls: false
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_auth_identity: ''

route:
  receiver: 'null'
  routes:
    - group_by: [job, alertname, severity]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: email-alerts
      matchers:
        - alertname != Watchdog
    - receiver: watchdog
      group_wait: 0s
      group_interval: 5m
      repeat_interval: 5m
      matchers:
        - alertname = Watchdog

receivers:
  - name: 'null'
  - name: email-alerts
    email_configs:
      - to: beavercloud@fastmail.com
  - name: watchdog
    webhook_configs:
      - url_file: /run/secrets/webhook_url
        send_resolved: false
