---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storage
namePrefix: dropbox-

resources:
  - ./resources/dropbox.yml

configMapGenerator: []

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: dropbox
