---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ytdl-sub
namePrefix: ytdl-sub-

resources:
  - ./ytdl-sub.yml

components:
  - ../../components/nas-media

configMapGenerator:
  - name: config
    files:
      - ./config/config.yaml
      - ./config/subscriptions.yaml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: ytdl-sub
