---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system
namePrefix: pv-backup-

resources:
  - ./resources/pv-backup.yml

configMapGenerator: []

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: pv-backup
