---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps
namePrefix: dev-top-

resources:
  - ./resources/dev-top.yml

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - dev-top.yml=gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: dev-top
