---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatus
namePrefix: gatus-

resources:
  - ./gatus.yml

components:
  - ../../components/pod-hardening

configMapGenerator:
  - name: config
    files:
      - ./config/gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: gatus
