---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant
namePrefix: home-assistant-

resources:
  - ./home-assistant.yml

components:
  - ../../components/pod-hardening
  - ../../components/tmpdirs

configMapGenerator:
  - name: config
    files:
      - ./config/configuration.yaml
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - home-assistant.yml=gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: home-assistant
