---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alertmanager/app.yml
  - argocd/app.yml
  - cloudflared/app.yml
  - external-dns/app.yml
  - gatus/app.yml
  - gpu-operator/app.yml
  - grafana/app.yml
  - healthchecks/app.yml
  - kube-vip/app.yml
  - longhorn/app.yml
  - node-exporter/app.yml
  - node-feature-discovery/app.yml
  - pihole/app.yml
  - prometheus/app.yml
