---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      hostname: alertmanager
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
        - name: config-volume
          configMap:
            name: config
        - name: alertmanager-secret
          secret:
            secretName: alertmanager-secret
      containers:
        - name: alertmanager
          image: docker.io/prom/alertmanager@sha256:cc54cc450174ada901b32eb2538de5fc70ee259a1ac551ed38023f2ca2ad00e3
          resources:
            requests:
              memory: 50M
            limits:
              memory: 500M
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
            - --web.external-url=https://alertmanager.beaver-cloud.xyz
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
            - name: data-volume
              mountPath: /alertmanager
            - name: alertmanager-secret
              mountPath: /run/secrets/webhook_url
              subPath: deadmans-switch
              readOnly: true
          ports:
            - name: web
              containerPort: 9093

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-replicated
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: service
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: web
      port: 80
      targetPort: web

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
spec:
  ingressClassName: internal
  tls:
    - hosts: [&host alertmanager.beaver-cloud.xyz]
      secretName: *host
  rules:
    - host: *host
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: service
                port:
                  name: web

---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: secret
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  organizationId: 575f69b2-49f4-456d-bd6f-b14101103188
  secretName: alertmanager-secret
  map:
    - secretKeyName: deadmans-switch
      bwSecretId: 9eb00cb7-2014-4c70-9f76-b3fd00eda2f0
  authToken:
    secretName: bw-auth-token
    secretKey: token
