---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alertmanager
namePrefix: alertmanager-

resources:
  - ./alertmanager.yml

components:
  - ../../components/pod-hardening

configMapGenerator:
  - name: config
    files:
      - ./config/alertmanager.yml
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - alertmanager.yml=gatus.yml

commonLabels:
  app.kubernetes.io/name: alertmanager
