apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps
namePrefix: immich-

resources:
  - ./resources/immich.yml
  - ./resources/postgres.yml
  - ./resources/redis.yml

configMapGenerator:
  - files:
      - immich.yml=gatus.yml
    name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: immich
