---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
    nginx.ingress.kubernetes.io/proxy-ssl-verify: 'off'
spec:
  rules:
    - host: host
      http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: service
                port:
                  name: https
