---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: ingress.yml
  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /spec/ports/0
        value:
          name: https
          port: 443
          targetPort: https
