---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./frigate/app.yml
  - ./home-assistant/app.yml
  - ./jellyfin/app.yml
  - ./template/app.yml
  - ./ytdl-sub/app.yml
