---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ai
  - ./apps
  - ./argocd
  - ./bitwarden-secrets
  - ./kube-system
  - ./kubevirt
  - ./media
  - ./networking
  - ./node-feature-discovery
  - ./gpu-operator
  - ./monitoring
  - ./ingress-nginx
  - ./cert-manager
  - ./openebs
  - ./external-secrets
  - ./storage
  - ./tailscale
  - ./cdi
  - ./snapscheduler
  - ./dev-top/app.yml
  - ./handbrake-web/app.yml
  - ./radarr/app.yml
  - ./sonarr/app.yml
  - ./template/app.yml
