---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./template/app.yml
  # - ./handbrake-web/app.yml
  # - ./radarr/app.yml
  # - ./sonarr/app.yml
  # - ./paperless-ngx/app.yml
