---
mqtt:
  enabled: false

detect:
  enabled: true

auth:
  enabled: false

ffmpeg:
  hwaccel_args: preset-nvidia-h264

detectors:
  onnx:
    type: onnx

record:
  enabled: true
  retain:
    days: 1
    mode: all
  alerts:
    retain:
      days: 1
      mode: motion
  detections:
    retain:
      days: 1
      mode: motion

model:
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt
  width: 320
  height: 320
  input_tensor: nchw
  input_pixel_format: bgr
  model_type: yolonas

go2rtc:
  streams:
    doorbell:
      - rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.1/Preview_01_main
    doorbell_sub:
      - rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.1/Preview_01_sub
    garage:
      - rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.2/Preview_01_main
    garage_sub:
      - rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.50.2/Preview_01_sub
    livingroom:
      - rtsp://thingino:thingino@192.168.50.11:554/ch0
    livingroom_sub:
      - rtsp://thingino:thingino@192.168.50.11:554/ch1

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles: [detect]
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/garage_sub
          input_args: preset-rtsp-restream
          roles: [detect]
  livingroom:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/livingroom
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/livingroom_sub
          input_args: preset-rtsp-restream
          roles: [detect]
