---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: syncthing
namePrefix: syncthing-

resources:
  - ./syncthing.yml

configMapGenerator:
  - name: gatus
    options:
      labels:
        gatus.io/enabled: 'true'
    files:
      - syncthing.yml=gatus.yml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: syncthing
