---
global:

route:
  group_by: [job, alertname, severity]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: ntfy

receivers:
  - name: 'null'
  - name: ntfy
    webhook_configs:
      - url: http://127.0.0.1:8000/hook
