---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../nas

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/volumes/0
        value:
          name: nas
          persistentVolumeClaim:
            claimName: nas
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/0
        value:
          name: nas
          mountPath: /media
          subPath: frigate
    target:
      kind: Deployment
