# SPDX-License-Identifier: MIT-0
---
- name: Restart k3s
  ansible.builtin.systemd_service:
    name: '{{ (k3s_role == "agent") | ternary("k3s-agent.service", "k3s.service") }}'
    daemon_reload: true
    state: restarted
